import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Montserrat} from 'next/font/google';
import Footer from "@/componentes/Footer/Footer";
import Header from "@/componentes/Header/Header";

const montserrat = Montserrat({ subsets: ['latin']});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
      <Header />
        {children}
      <Footer />  
      </body>
    </html>
  );
}
